return {
    "31.01.2023",
	"(+) Fixed UI Libs",
	"(+) Fixed Key System",
	"(-) Old Key System UI",
	"(-) Old Loader UI",
	"(+) New Hawk Launcher UI",
	"(+) New Key System UI",
	"",
	"30.01.2023",
	"(+) Added Lucky Blocks Script",
	"",
	"29.01.2023",
	"(+) Fixed Script",
	"(+) Disabled Key System",
	"",
    "28.01.2023",
	"(+) Fixed Key System",
    "(+) Changed Premium",
	"",
	"12.01.2023",
	"(+) Fixed Exploit Support",
	"",
	"09.01.2023",
	"(+) Fixed Loader",
	"",
	"08.01.2023",
	"(+) Fixed Lag Problem",
	"",
	"07.01.2023",
	"(+) Fixed Loader",
	"",
	"29.12.2022",
	"(+) Fixed Synapse Support",
	"",
	"27.12.2022",
	"(+) Fixed Mobile Loader",
	"(+) Fixed Mobile",
	"(+) Fixed Color Pickers (Mobile)",
	"",
	"23.12.2022",
	"(+) Fixed Hawk HUB",
	"(+) New Key System UI",
	"(+) Fixed Website",
	"",
	"19.12.2022",
	"(+) Added Anti Hb remover (Skywars)",
	"(+) Added Fly (Skywars)",
	"(+) Added Infinite Yield (Skywars)",
	"",
	"18.12.2022",
	"(+) Added Target Player (Skywars)",
	"(+) Added Black Hole (Skywars)",
	"18.12.2022",
	"(+) Fixed Key System",
	"18.12.2022",
	"(+) Fixed Synapse X Support",
	"",
	"17.12.2022",
	"(+) Fixed Click Glitch (UI Libs)",
	"(+) Fixed Key System",
	"",
	"15.12.2022",
	"(+) Fixed Not Opening (Pc and Mobile)",
	"",
	"14.12.2022",
	"(+) Fixed Mobile",
	"(+) Re Added Key System To Mobile",
	"(+) Fixed Skywars (Mobile)",
	"",
	"11.12.2022",
	"(+) Fixed Mobile",
	"(+) Added Hydrogen Support",
	"(+) Fixed Mobile Lib",
	"(-) Removed Key System From Mobile",
	"(+) Fixed Loader",
	"11.12.2022",
	"(+) Fixed Loader",
	"(+) Fixed Not Showing Bug",
	"(+) Readded Hawk Loader UI",
	"(+) Added Universal",
	"(+) Fixed Mobile",
	"(+) Fixed Pc",
	"11.12.2022",
	"(+) Updated Skywars",
	"Updated Ore Esp",
	"(+) Updated Murder Mystery 2",
	"Added Kill Sheriff",
	"Fixed Gun Esp",
	"",
	"09.12.2022",
	"(+) Fixed Color Pickers",
	"(+) Fixed Lag Problem",
	"09.12.2022",
	"(+) Fixed UI Libs!",
	"(+) Fixed Loader",
	"(+) Changed Website to hawksoftworks.ga",
	"(+) Fixed Obfuscators",
	"(+) Fixed Website",
	"",
	"02.12.2022",
	"(+) Fixed Key System!",
	"(+) Fixed Loader",
	"(+) Changed Website to hawksoftworks.ga",
	"(+) Fixed Admin",
	"",
	"29.11.2022",
	"(+) Fixed Mobile!",
	"(+) Fixed Mobile Key System",
	"(+) Fixed Mobile Loader!",
	"(+) Rewrited Device Detection",
	"",
	"27.11.2022",
	"(+) Added Key System To Website!",
	"(+) Added Key System",
	"(+) Fixed Loader!",
	"(+) Added Key Saver",
	"",
	"25.11.2022",
	"(-) Removed Key System From Website!",
	"(+) Fixed Loader!",
	"(-) Removed Key System",
	"",
	"24.11.2022",
	"(+) Added Key System To Website!",
	"(+) Fixed Loader!",
	"(-) Removed Key Saver",
	"(+) Added Mini Loader!",
	"",
	"19.11.2022",
	"(+) Created The Website",
	"(+) Added Hawk and LightuxCrack Pages!",
	"",
	"17.11.2022",
	"(+) Added Key System (Basically, without website",
	"(+) Fixed Loader",
	"",
	"15.11.2022",
	"(+) Changed Loader Credits",
	"(+) Fixed Hawk Admin",
	"(+) Fixed Skywars",
	"15.11.2022",
	"(*) A problem reported by VitaminBitter",
	"(*) Working on Problem",
	"(+) Problem is fixed",
	"(+) Fixed UI Libs",
	"",
	"14.11.2022",
	"(+) Ui Libs Fixed",
	"(+) Key System Added",
	"(+) Game (Kat) Added",
	"(+) Fixed Air Block (Skywars)",
	"(+) Added Reach (Skywars)",
	"",
	"12.11.2022",
	"(*) New Loader Created",
	"(*) Key System Created",
	"",
	"15.10.2022",
	"(+) Ui Libs Fixed",
	"(+) Added New Loader",
	"(+) Added Air Block To Skywars",
	"(-) Removed Old Loader",
	"",
	"06.10.2022",
	"(+) Kick Off Added",
	"(+) Mad City Added",
	"",
	"16.09.2022",
	"(+) Fnaf Five Nights Simulator Added",
	"",
	"15.08.2022",
	"(+) Loader Fixed",
	"",
	"05.06.2022",
	"(+) Hawk HUB is Created",
	"(+) First Loader is released!",
	"(+) Hawk HUB Showcase (Deleted)",
}
